# This is the configuration file for Gammapy on Azure Pipelines

jobs:

- job: 'Test'

  strategy:
    matrix:
      Python27:
        imageName: 'ubuntu-16.04'
        python.version: '2.7'
      Python35:
        imageName: 'ubuntu-16.04'
        python.version: '3.5'
      Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.7'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install pytest pytest-cov cython numpy astropy regions pyyaml click pytest-astropy
    displayName: 'Install dependencies'

  - script: |
      pip install -e .
      pytest gammapy --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
