# Conda environment for Gammapy stable versions
# Install:    conda env create -f environment.yml
# Activate:   source activate gammapy-master
# Deactivate: source deactivate

name: gammapy-master

channels:
  - conda-forge
  - sherpa

dependencies:
  - python==3.6
  - ipython==6.5.0
  - jupyter==1.0.0
  - jupyterlab==0.33.8
  - jupyterlab_launcher==0.11.2
  - cython==0.28.5
  - numpy==1.13
  - astropy==3.0.4
  - regions==0.3
  - click==6.7
  - pyyaml==3.12
  - scipy==0.19.1
  - reproject==0.4
  - uncertainties==3.0.2
  - naima==0.8.1
  - iminuit==1.3.2
  - sherpa==4.10
  - healpy==1.11.0
  - matplotlib==2.2.3
  - pandas==0.23.4
  
  - pip:
    - git+https://github.com/gammapy/gammapy.git#egg=gammapy
