# Conda environment for Gammapy development
#
# Install:    conda env create -f environment-dev.yml
# Update:     conda env update -f environment-dev.yml
# Activate:   conda activate gammapy-dev
# Deactivate: conda deactivate

name: gammapy-dev

channels:
  - conda-forge
  - sherpa

dependencies:
  # core dependencies
  - python==3.7
  - pip
  - astropy
  - click
  - cython
  - numpy
  - pydantic
  - pyyaml
  - regions
  - scipy
  # test dependencies
  - codecov
  - pytest
  - pytest-astropy
  - pytest-cov
  - pytest-sphinx
  - pytest-xdist
  # extra dependencies
  - healpy
  - iminuit<2.0
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - naima
  - pandas
  - parfive
  - reproject
  - requests
  - sherpa
  - tqdm
  # dev dependencies
  - black
  - flake8
  - isort
  - nbsphinx
  - numdifftools
  - pandoc
  - pydocstyle
  - pylint
  - setuptools_scm
  - sphinx==2.4.4
  - sphinx-astropy
  - sphinx-click
  - sphinx-gallery
  - sphinx_rtd_theme
  - twine
  - yamllint
