data:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    obs_cone: {frame: icrs, lon: 83.633 deg, lat: 22.014 deg, radius: 5 deg}

datasets:
    type: 3d
    stack: true
    geom:
        wcs:
            skydir: {frame: icrs, lon: 83.633 deg, lat: 22.014 deg}
            binsize: 0.04 deg
            fov: {width: 5 deg, height: 5 deg}
            binsize_irf: 0.2 deg
            margin_irf: 0.5 deg
        selection:
            offset_max: 2.5 deg
        axes:
            energy: {min: 1 TeV, max: 10 TeV, nbins: 4}
            energy_true: {min: 1 TeV, max: 10 TeV, nbins: 5}

fit:
    fit_range: {min: 1 TeV, max: 10 TeV}

flux_points:
    energy: {min: 1 TeV, max: 10 TeV, nbins: 2}
