observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    obs_cone: {frame: icrs, lon: 83.633 deg, lat: 22.014 deg, radius: 5 deg}

datasets:
    type: 1d
    stack: false
    geom:
        axes:
            energy: {min: 0.01 TeV, max: 100 TeV, nbins: 73}
    background:
        method: reflected
    on_region: {frame: icrs, lon: 83.633 deg, lat: 22.014 deg, radius: 0.1 deg}
    containment_correction: true
    psf_kernel_radius: 0.6 deg

fit:
    fit_range: {min: 0.1 TeV, max: 100 TeV}

flux_points:
    energy: {min: 1 TeV, max: 10 TeV, nbins: 11}
