---
general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    filters:
        - filter_type: par_value
          value_param: Crab
          variable: TARGET_NAME

reduction:
    background:
        background_estimator: reflected
        on_region:
            center:
                - 83.633 deg
                - 22.014 deg
            frame: icrs
            radius: 0.1 deg
    data_reducer: 1d

geometry:
    axes: {}

model:
    components:
        - name: source
          spatial:
              parameters:
                  - frozen: true
                    name: lon_0
                    scale: 1.0
                    unit: deg
                    value: 83.633
                  - frozen: true
                    name: lat_0
                    scale: 1.0
                    unit: deg
                    value: 22.14
              type: SkyPointSource
          spectral:
              parameters:
                  - factor: 2.0
                    frozen: false
                    name: index
                    scale: 1.0
                    unit: ''
                    value: 2.0
                  - factor: 1.0e-12
                    frozen: false
                    name: amplitude
                    scale: 1.0
                    unit: cm-2 s-1 TeV-1
                    value: 1.0e-12
                  - factor: 1.0
                    frozen: true
                    name: reference
                    scale: 1.0
                    unit: TeV
                    value: 1.0
              type: PowerLaw
          type: SkyModel

fit:
    fit_range:
        max: 100 TeV
        min: 1 TeV

flux:
    fp_binning:
        hi_bnd: 10
        interp: log
        lo_bnd: 1
        nbin: 11
        unit: TeV
