---
general:
  logging:
    level: INFO
  outdir: .

observations:
  datastore: $GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz
  filters:
  - filter_type: par_value
    value_param: Crab
    variable: TARGET_NAME

reduction:
  data_reducer: 3d

geometry:
  axes:
    e_reco:
      hi_bnd: 10
      interp: log
      lo_bnd: 1
      name: energy
      nbin: 4
      node_type: edges
      unit: TeV
  binsz: 0.02
  coordsys: CEL
  offset_max: 2.5 deg
  proj: TAN
  psf_max_radius: 0.3 deg
  skydir:
  - 83.633
  - 22.014
  width:
  - 5
  - 5

model:
  components:
  - name: source
    spatial:
      parameters:
      - frozen: false
        max: 85
        min: 80
        name: lon_0
        scale: 1.0
        unit: deg
        value: 83.633
      - frozen: false
        max: 24
        min: 20
        name: lat_0
        scale: 1.0
        unit: deg
        value: 22.14
      type: SkyPointSource
    spectral:
      parameters:
      - factor: 2.0
        frozen: false
        name: index
        scale: 1.0
        unit: ''
        value: 2.6
      - factor: 1.0e-12
        frozen: false
        name: amplitude
        scale: 1.0
        unit: cm-2 s-1 TeV-1
        value: 5.0e-11
      - factor: 1.0
        frozen: true
        name: reference
        scale: 1.0
        unit: TeV
        value: 1.0
      type: PowerLaw
    type: SkyModel

fit: {}

flux: {}
