---
"$schema": "http://json-schema.org/schema#"
"title": "Schema validation for Gammapy high-level interface API configuration"

type: object
additionalProperties: false
properties:

    general:
        description: ""
        type: object
        default: {"logging": {}}
        additionalProperties: false
        properties:
            out_folder:
                description: ""
                type: string
                default: "."

            logging:
                description: ""
                type: object
                default: {"level": ""}
                additionalProperties: false
                properties:
                    level:
                        description: ""
                        type: string
                        default: INFO
                        enum: [CRITICAL, 50,
                               ERROR, 40,
                               WARNING, 30,
                               INFO, 20,
                               DEBUG, 10,
                               NOTSET]
                    filename: {type: string}
                    filemode: {type: string}
                    format: {type: string}
                    datefmt: {type: string}
                required: [level]
                dependencies:
                    filemode: [filename]
        required: [logging]

    # ---

    observations:
        type: object

    grid:
        type: object

    model:
        type: object

    analysis:
        type: object

required: [general]

# ---
definitions:
    prop:
        enum: [values]