---
"$schema": "http://json-schema.org/schema#"
"title": "Schema validation for Gammapy high-level interface API configuration"

type: object
additionalProperties: true
properties:

    general:
        description: "General settings for the API."
        type: object
        default: {"logging": {}}
        additionalProperties: false
        properties:
            out_folder:
                description: "Output folder where files will be stored."
                type: string
                default: "."
            logging:
                description: "Logging settings for the session."
                type: object
                default: {"level": ""}
                additionalProperties: false
                properties:
                    level:
                        description: ""
                        type: string
                        default: INFO
                        enum: [CRITICAL, 50,
                               ERROR, 40,
                               WARNING, 30,
                               INFO, 20,
                               DEBUG, 10,
                               NOTSET]
                    filename: {type: string}
                    filemode: {type: string}
                    format: {type: string}
                    datefmt: {type: string}
                required: [level]
                dependencies:
                    filemode: [filename]
        required: [logging]

    observations:
        description: "Observations used in the analysis."
        type: object
        default: {}
        additionalProperties: false
        properties:
            data_store:
                description: "Data store where to fetch observations."
                type: string
                default: $GAMMAPY_DATA/cta-1dc/index/gps/
            filter:
                description: "Array of filter criteria to select observations."
                type: array
                default: [{}]
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        exclude: {type: boolean}
                        inverted: {type: boolean}
                        filter_type:
                            default: all
                            enum: [sky_circle,
                                   angle_box,
                                   par_box,
                                   ids,
                                   all]
                        frame:
                            enum: [galactic, equatorial, icrs, fk5]
                        lon: {type: number}
                        lat: {type: number}
                        radius: {type: number}
                        border: {type: number}
                        variable: {type: string}
                        value_range:
                            type: array
                            items: {type: number}
                            minItems: 2
                            maxItems: 2
                        obs_ids:
                            type: array
                            items: {type: integer}
                            default: []
                    required: [filter_type]
        required: [data_store]

    grid:
        type: object

    model:
        type: object

    analysis:
        type: object

required: [general, observations]
