---
"$schema": "http://json-schema.org/schema#"
"title": "Schema validation for Gammapy high-level interface API configuration"

type: object
additionalProperties: true
properties:

    general:
        description: "General settings for the API."
        type: object
        default: {"logging": {}}
        additionalProperties: false
        properties:
            outdir:
                description: "Output folder where files will be stored."
                type: string
                default: "."
            logging:
                description: "Logging settings for the session."
                type: object
                default: {"level": ""}
                additionalProperties: false
                properties:
                    level:
                        description: ""
                        type: string
                        default: INFO
                        enum: [CRITICAL, 50,
                               ERROR, 40,
                               WARNING, 30,
                               INFO, 20,
                               DEBUG, 10,
                               NOTSET]
                    filename: {type: string}
                    filemode: {type: string}
                    format: {type: string}
                    datefmt: {type: string}
                required: [level]
                dependencies:
                    filemode: [filename]
        required: [logging]

    observations:
        description: "Observations used in the analysis."
        type: object
        default: {}
        additionalProperties: false
        properties:
            datastore:
                description: "Data store where to fetch observations."
                type: string
                default:
                    $GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz
            filters:
                description: "Array of filters with selection criteria."
                type: array
                default: [{}]
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        exclude: {type: boolean}
                        inverted: {type: boolean}
                        filter_type:
                            default: par_value
                            enum: [sky_circle,
                                   angle_box,
                                   par_box,
                                   par_value,
                                   ids,
                                   all]
                        frame:
                            default: icrs
                            enum: [galactic, equatorial, icrs, fk5]
                        lon: {type: number, default: 83.633 deg}
                        lat: {type: number, default: 22.014 deg}
                        radius: {type: number}
                        border: {type: number}
                        variable: {type: string, default: TARGET_NAME}
                        value_param: {type: string, default: Crab}
                        value_range:
                            type: array
                            items: {type: number}
                            minItems: 2
                            maxItems: 2
                        obs_ids:
                            type: array
                            items: {type: integer}
                            default: []
                    required: [filter_type]
        required: [datastore]

    reduction:
        description: "Process of data reduction."
        type: object
        default: {}
        additionalProperties: false
        properties:
            background:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    background_estimator:
                        default: reflected
                        enum: [reflected, ring]
                    on_region:
                        type: object
                        default: {}
                        additionalProperties: false
                        properties:
                            center:
                                type: array
                                items: {type: number}
                                default: [83.633 deg, 22.014 deg]
                                minItems: 2
                                maxItems: 2
                            radius:
                                type: number
                                default: 0.1 deg
                            frame:
                                default: icrs
                                enum: [galactic, equatorial, icrs, fk5]
                    exclusion_mask:
                        description: "Filename of a FITS file."
                        type: object
                        additionalProperties: false
                        properties:
                            filename:
                                type: string
                            hdu:
                                type: string
                if:
                    properties:
                        exclusion_mask:
                            required: [filename]
            data_reducer:
                default: 1d
                enum: [1d, 2d, 3d]
            containment_correction:
                type: boolean
                default: true
        if:
            properties:
                data_reducer:
                    const: 1d
        then:
            properties:
                background:
                    required: [background_estimator, on_region]

    geometry:
        description: "Geometry where to perform data reduction and analysis."
        type: object
        additionalProperties: false
        properties:
            binsz:
                description: "Map pixel size in degrees."
                type: number
            coordsys:
                description: "Coordinate system."
                type: string
                enum: [CEL, GAL]
            proj:
                description: "Any valid WCS projection type."
                type: string
            skydir:
                description: "Lon and lat in deg in the coordsys of the map."
                type: array
                items: {type: number}
                minItems: 2
                maxItems: 2
            width:
                description: "Width of the map in degrees."
                type: array
                items: {type: number}
                minItems: 1
                maxItems: 2
            offset_max:
                type: number
            axes:
                type: object
                additionalProperties: false
                properties:
                    e_reco:
                        type: array
                        items: {type: number}
                    e_true:
                        type: array
                        items: {type: number}

    model:
        type: object

required: [general, observations]
