---
"$schema": "http://json-schema.org/schema#"
"title": "Schema validation for Gammapy high-level interface API configuration"

type: object
additionalProperties: true
properties:

# Block: general
# General settings for the API
#
#    Logging settings for the session
#    Example values for the following properties
#    logging:
#        level: CRITICAL, ERROR, WARNING, INFO, DEBUG
#        filename: filename.log
#        filemode: w
#        format: "%(asctime)s - %(message)s"
#        datefmt: "%d-%b-%y %H:%M:%S"
#
#    Output folder where files will be stored
#    outdir:
#
    general:
        type: object
        default: {"logging": {}}
        additionalProperties: false
        properties:
            outdir: {type: string, default: "."}
            logging:
                type: object
                default: {"level": ""}
                additionalProperties: false
                properties:
                    level:
                        description: ""
                        type: string
                        default: INFO
                        enum: [CRITICAL, 50,
                               ERROR, 40,
                               WARNING, 30,
                               INFO, 20,
                               DEBUG, 10,
                               NOTSET]
                    filename: {type: string, default: filename.log}
                    filemode: {type: string, default: w}
                    format: {type: string, default: "%(asctime)s - %(message)s"}
                    datefmt: {type: string, default: "%d-%b-%y %H:%M:%S"}
                required: [level]
                dependencies:
                    filemode: [filename]
        required: [logging]

# Block: observations
# Observations used in the analysis
#
#    Path to data store where to fetch observations
#    datastore:
#
#    List of filters with selection criteria
#    Example values for the following properties
#    filters:
#
#        - filter_type: sky_circle, angle_box, par_box, par_value, ids, all
#          Type of filter used
#
#          Properties when filter_type is "par_box"
#          frame: galactic, equatorial, icrs, fk5
#          lon: 83.633 deg
#          lat: 22.014 deg
#          radius: 1 deg
#          border: 1 deg
#
#          Properties when filter_type is "par_box" or "par_value"
#          variable: TARGET_NAME
#
#          Value parameter to match declared variable when filter_type is "par_value"
#          value_param: Crab
#
#          Value range with units to match declared variable when filter_type is "par_box"
#          value_range:
#              - 265 deg
#              - 268 deg
#
#          List of observation identifiers when filter_type is "ids"
#          obs_ids:
#              - 23523
#              - 23526
#
#          inverted: true for not matching criteria
#          exclude: true to exclude matched observations
#
    observations:
        type: object
        default: {}
        additionalProperties: false
        properties:
            datastore:
                type: string
                default:
                    $GAMMAPY_DATA/hess-dl3-dr1
            filters:
                type: array
                default: [{}]
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        exclude: {type: boolean, default: false}
                        inverted: {type: boolean, default: false}
                        filter_type:
                            default: par_value
                            enum: [sky_circle,
                                   angle_box,
                                   par_box,
                                   par_value,
                                   ids,
                                   all]
                        frame:
                            default: icrs
                            enum: [galactic, equatorial, icrs, fk5]
                        lon: {type: number, default: 83.633 deg}
                        lat: {type: number, default: 22.014 deg}
                        radius: {type: number, default: 0.5 deg}
                        border: {type: number, default: 0.5 deg}
                        variable: {type: string, default: TARGET_NAME}
                        value_param: {type: string, default: Crab}
                        value_range:
                            type: array
                            items: {type: number, default:[1 TeV, 100 TeV]}
                            minItems: 2
                            maxItems: 2
                        obs_ids:
                            type: array
                            items: {type: integer, default: [23523, 23526]}
                    required: [filter_type]
        required: [datastore]

# Block: reduction
# Process of data reduction
#
#    Chosen data reducer process
#    data_reducer: 1d, 2d, 3d
#
#    Parameters used in the estimation of the background
#    Example values for the following properties
#    background:
#
#        background_estimator: reflected
#        on_region:
#            center:
#            - 83.633 deg
#            - 22.014 deg
#            frame: icrs
#            radius: 0.11 deg
#        exclusion_mask
#            filename: mask.fits
#            hdu: IMAGE
#
#    containment_correction: true
#
    reduction:
        type: object
        default: {}
        additionalProperties: false
        properties:
            background:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    background_estimator:
                        default: reflected
                        enum: [reflected, ring]
                    on_region:
                        type: object
                        default: {}
                        additionalProperties: false
                        properties:
                            center:
                                type: array
                                items: {type: number}
                                default: [83.633 deg, 22.014 deg]
                                minItems: 2
                                maxItems: 2
                            radius: {type: number, default: 0.1 deg}
                            frame:
                                default: icrs
                                enum: [galactic, equatorial, icrs, fk5]
                    exclusion_mask:
                        type: object
                        default: {}
                        additionalProperties: false
                        properties:
                            filename: {type: string, default: filename.fits}
                            hdu: {type: string, default: IMAGE}
                if:
                    properties:
                        exclusion_mask:
                            required: [filename]
            data_reducer:
                default: 1d
                enum: [1d, 2d, 3d]
            containment_correction: {type: boolean, default: false}
        if:
            properties:
                data_reducer:
                    const: 1d
        then:
            properties:
                background:
                    required: [background_estimator, on_region]

# Block: geometry
# Geometry where to perform data reduction and analysis
#
#        Map pixel size in degrees
#        binsz: 0.02
#        Coordinate system
#        coordsys: CEL, GAL
#        Any valid WCS projection type
#        proj: CAR
#        Lon and lat in deg in the coordsys of the map
#        skydir: [83, 22]
#        Width of the map in degrees
#        width: [5, 5]
#        offset_max: 3 deg
#
#        Additional Map Axes other than spatial
#        Example values for energy axes
#        axes:
#            e_reco:
#                lo_bnd: 0.01
#                hi_bnd: 100
#                nbin: 73
#                unit: TeV
#                interp: log
#            e_true:
#                lo_bnd: 0.01
#                hi_bnd: 315
#                nbin: 109
#                unit: TeV
#                interp: log
#
    geometry:
        description: ""
        type: object
        default: {}
        additionalProperties: false
        properties:
            binsz: {type: number, default: 0.02}
            coordsys:
                type: string
                default: CEL
                enum: [CEL, GAL]
            proj: {type: string, default: CAR}
            skydir:
                type: array
                items: {type: number, default: [83, 22]}
                minItems: 2
                maxItems: 2
            width:
                type: array
                items: {type: number, default: [5, 5]}
                minItems: 1
                maxItems: 2
            offset_max: {type: number, default: 3 deg}
            axes:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    e_reco:
                        type: object
                        default: {}
                        additionalProperties: false
                        properties:
                            name: {type: string, default: e_reco}
                            lo_bnd: {type: number, default: 0.01}
                            hi_bnd: {type: number, default: 100}
                            nbin: {type: number, default: 73}
                            unit: {type: string, default: TeV}
                            interp:
                                type: string
                                default: log
                                enum: [lin, log, sqrt]
                            node_type:
                                type: string
                                default: center
                                enum: [edges, center]
                        required: [lo_bnd, hi_bnd, nbin, unit]
                    e_true:
                        type: object
                        default: {}
                        additionalProperties: false
                        properties:
                            name: {type: string, default: e_true}
                            lo_bnd: {type: number, default: 0.01}
                            hi_bnd: {type: number, default: 315}
                            nbin: {type: number, default: 109}
                            unit: {type: string, default: TeV}
                            interp:
                                type: string
                                default: log
                                enum: [lin, log, sqrt]
                            node_type:
                                type: string
                                default: center
                                enum: [edges, center]
                        required: [lo_bnd, hi_bnd, nbin, unit]

# Block: model
# Parameters that define the models used in the analysis process
# List of models with spatial and /or spectral components
# TODO
#
    model:
        type: object
        default: {}
        additionalProperties: false
        properties:
            components:
                type: array
                default: [{}]
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        name: {type: string, default: source}
                        spatial:
                            type: object
                            default: {}
                            additionalProperties: false
                            properties:
                                type: {type: string, default: SkyGaussian}
                                parameters:
                                    type: array
                                    default:
                                        - factor: 0.0
                                          frozen: false
                                          max: 180.0
                                          min: -180.0
                                          name: lon_0
                                          scale: 1.0
                                          unit: deg
                                          value: 0.0
                                        - factor: 0.0
                                          frozen: false
                                          max: 90.0
                                          min: -90.0
                                          name: lat_0
                                          scale: 1.0
                                          unit: deg
                                          value: 0.0
                                        - factor: 1.0
                                          frozen: false
                                          max: .nan
                                          min: 0.0
                                          name: sigma
                                          scale: 1.0
                                          unit: deg
                                          value: 1.0
                                    items:
                                        type: object
                                        additionalProperties: false
                                        properties:
                                            name: {type: string}
                                            value: {type: number}
                                            factor: {type: number}
                                            scale: {type: number}
                                            unit: {type: string}
                                            min: {type: number}
                                            max: {type: number}
                                            frozen: {type: boolean}
                        spectral:
                            type: object
                            default: {}
                            additionalProperties: false
                            properties:
                                type: {type: string, default: PowerLaw}
                                parameters:
                                    type: array
                                    default:
                                        - factor: 2.0
                                          frozen: false
                                          max: .nan
                                          min: .nan
                                          name: index
                                          scale: 1.0
                                          unit: ''
                                          value: 2.0
                                        - factor: 1.0e-12
                                          frozen: false
                                          max: .nan
                                          min: .nan
                                          name: amplitude
                                          scale: 1.0
                                          unit: cm-2 s-1 TeV-1
                                          value: 1.0e-12
                                        - factor: 1.0
                                          frozen: true
                                          max: .nan
                                          min: .nan
                                          name: reference
                                          scale: 1.0
                                          unit: TeV
                                          value: 1.0
                                    items:
                                        type: object
                                        additionalProperties: false
                                        properties:
                                            name: {type: string}
                                            value: {type: number}
                                            factor: {type: number}
                                            scale: {type: number}
                                            unit: {type: string}
                                            min: {type: number}
                                            max: {type: number}
                                            frozen: {type: boolean}
# Block: fit
# Parameters that are used in the fitting process
#
#        Energy range considered, min and max values with units
#        fit_range:
#            min: 1 TeV
#            max: 100 Tev
#
    fit:
        type: object
        additionalProperties: false
        default: {}
        properties:
            fit_range:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    min: {type: number, default: 1 TeV}
                    max: {type: number, default: 100 TeV}

# Block: flux
# Parameters that are used during the flux estimation process
#
#        Energy binning considered
#        fp_binning:
#            lo_bnd: 1
#            hi_bnd: 10
#            nbin: 11
#            unit: TeV
#            interp: log
#
    flux:
        type: object
        additionalProperties: false
        default: {}
        properties:
            fp_binning:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    name: {type: string, default: flux_binning}
                    lo_bnd: {type: number, default: 1}
                    hi_bnd: {type: number, default: 10}
                    nbin: {type: number, default: 11}
                    unit: {type: string, default: TeV}
                    interp:
                        type: string
                        default: log
                        enum: [lin, log, sqrt]
                    node_type:
                        type: string
                        default: edges
                        enum: [edges, center]
                required: [lo_bnd, hi_bnd, nbin, unit]

required: [general, observations]
