---
general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    filters:
        - filter_type: all

reduction:
    data_reducer: not assigned

geometry:
    axes: {}

model: gammapy/scripts/config/model.yaml

fit:
    fit_range: {}

flux: {}
