---
general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz
    filters:
        - filter_type: par_value
          value_param: Crab
          variable: TARGET_NAME

reduction:
    dataset-type: MapDataset
    stack-datasets: true
    offset-max: 2.5 deg
    geom:
        skydir: [83.633, 22.014]
        width: [5, 5]
        binsz: 0.02
        coordsys: CEL
        proj: TAN
        axes:
          - name: energy
            hi_bnd: 10
            lo_bnd: 1
            nbin: 4
            interp: log
            node_type: edges
            unit: TeV
    geom-irf:
        skydir: [83.633, 22.014]
        width: [5, 5]
        binsz: 0.2
        coordsys: CEL
        proj: TAN
        axes:
            - name: energy
              hi_bnd: 10
              lo_bnd: 1
              nbin: 11
              interp: log
              node_type: center
              unit: TeV

model: model.yaml

fit: {}

flux: {}
