name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GAMMAPY_DATA: /home/runner/work/gammapy/gammapy/gammapy-datasets
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: create and activate env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gammapy-dev
          environment-file: environment-dev.yml
          auto-update-conda: true
      - name: install gammapy
        run: |
          pip install -e .
          gammapy info
      - name: download datasets
        run: gammapy download datasets --silent
      - name: test coverage
        run: |
          make test-cov
          codecov -X gcov
      - name: build docs
        run: make docs-all
