name: Build dev docs
on: push
jobs:
  dispatch-docs:
      runs-on: ubuntu-latest
      steps:
        - name: Dispatch Gammapy Docs
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.REMOTE_DISPATCH }}
            repository: gammapy/gammapy-docs
            event-type: dev-docs
            
