name: Run profiler on benchmarks
on: merge

jobs:
  dispatch-benchmarks:
    if: github.repository_owner == 'gammapy'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Gammapy Benchmarks
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REMOTE_DISPATCH }}
          repository: gammapy/gammapy-benchmarks
          event-type: dev-benchmarks
