name: Remote dispatch action on gammapy-benchmarks
on:
  pull_request:
    branches:
      - master
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch validation
        uses: mvasigh/dispatch-action@master
        with:
          token: ${{ secrets.REMOTE_DISPATCH }}
          repo: gammapy-benchmarks
          owner: gammapy
          event_type: validate
